import { createSignal, Show } from 'solid-js';

import "./code.scss";

import hljs from "highlight.js/lib/core";

export interface ICodeProps {
    src: string,
    language?: string,
}

function hasLang(lang: string | null | undefined | void): string | undefined {
    if(lang && hljs.getLanguage(lang)) {
        return lang;
    }
    return;
}

export default function Code(props: ICodeProps) {
    let language: () => string | undefined | void = () => { }, pending_language = props.language;

    if(pending_language && !hljs.getLanguage(pending_language) && LANGUAGES[pending_language]) {
        let [lang, setLang] = createSignal<string>();
        language = lang; // setup signal to trigger refresh

        LANGUAGES[pending_language]().then((l) => {
            if(!hljs.getLanguage(pending_language!)) {
                hljs.registerLanguage(pending_language!, l.default);
            }
            setLang(pending_language);
        });
    }

    return (
        <Show when={hasLang(language())} keyed fallback={
            <pre class="hljs">
                <code textContent={/* @once */props.src.trim()} />
            </pre>
        }>
            {language => <Highlight src={/* @once */props.src} language={/* @once */language} />}
        </Show>
    );
}

function Highlight(props: Required<ICodeProps>) {
    let compiled = hljs.highlight(props.src, { language: props.language });

    return (
        <pre class="hljs" data-language={/*@once*/compiled.language}>
            <code innerHTML={/* @once */compiled.value} />
        </pre>
    );
}

import type { LanguageFn } from 'highlight.js';

// == AUTOGENERATED BELOW THIS LINE ==
const LANGUAGES: { [language: string]: () => Promise<{ default: LanguageFn }> } = {
    "1c": () => import("highlight.js/lib/languages/1c.js"),
    "abnf": () => import("highlight.js/lib/languages/abnf.js"),
    "accesslog": () => import("highlight.js/lib/languages/accesslog.js"),
    "actionscript": () => import("highlight.js/lib/languages/actionscript.js"),
    "ada": () => import("highlight.js/lib/languages/ada.js"),
    "angelscript": () => import("highlight.js/lib/languages/angelscript.js"),
    "apache": () => import("highlight.js/lib/languages/apache.js"),
    "applescript": () => import("highlight.js/lib/languages/applescript.js"),
    "arcade": () => import("highlight.js/lib/languages/arcade.js"),
    "arduino": () => import("highlight.js/lib/languages/arduino.js"),
    "armasm": () => import("highlight.js/lib/languages/armasm.js"),
    "asciidoc": () => import("highlight.js/lib/languages/asciidoc.js"),
    "aspectj": () => import("highlight.js/lib/languages/aspectj.js"),
    "autohotkey": () => import("highlight.js/lib/languages/autohotkey.js"),
    "autoit": () => import("highlight.js/lib/languages/autoit.js"),
    "avrasm": () => import("highlight.js/lib/languages/avrasm.js"),
    "awk": () => import("highlight.js/lib/languages/awk.js"),
    "axapta": () => import("highlight.js/lib/languages/axapta.js"),
    "bash": () => import("highlight.js/lib/languages/bash.js"),
    "basic": () => import("highlight.js/lib/languages/basic.js"),
    "bnf": () => import("highlight.js/lib/languages/bnf.js"),
    "brainfuck": () => import("highlight.js/lib/languages/brainfuck.js"),
    "c": () => import("highlight.js/lib/languages/c.js"),
    "cal": () => import("highlight.js/lib/languages/cal.js"),
    "capnproto": () => import("highlight.js/lib/languages/capnproto.js"),
    "ceylon": () => import("highlight.js/lib/languages/ceylon.js"),
    "clean": () => import("highlight.js/lib/languages/clean.js"),
    "clojure-repl": () => import("highlight.js/lib/languages/clojure-repl.js"),
    "clojure": () => import("highlight.js/lib/languages/clojure.js"),
    "cmake": () => import("highlight.js/lib/languages/cmake.js"),
    "coffeescript": () => import("highlight.js/lib/languages/coffeescript.js"),
    "coq": () => import("highlight.js/lib/languages/coq.js"),
    "cos": () => import("highlight.js/lib/languages/cos.js"),
    "cpp": () => import("highlight.js/lib/languages/cpp.js"),
    "crmsh": () => import("highlight.js/lib/languages/crmsh.js"),
    "crystal": () => import("highlight.js/lib/languages/crystal.js"),
    "csharp": () => import("highlight.js/lib/languages/csharp.js"),
    "csp": () => import("highlight.js/lib/languages/csp.js"),
    "css": () => import("highlight.js/lib/languages/css.js"),
    "d": () => import("highlight.js/lib/languages/d.js"),
    "dart": () => import("highlight.js/lib/languages/dart.js"),
    "delphi": () => import("highlight.js/lib/languages/delphi.js"),
    "diff": () => import("highlight.js/lib/languages/diff.js"),
    "django": () => import("highlight.js/lib/languages/django.js"),
    "dns": () => import("highlight.js/lib/languages/dns.js"),
    "dockerfile": () => import("highlight.js/lib/languages/dockerfile.js"),
    "dos": () => import("highlight.js/lib/languages/dos.js"),
    "dsconfig": () => import("highlight.js/lib/languages/dsconfig.js"),
    "dts": () => import("highlight.js/lib/languages/dts.js"),
    "dust": () => import("highlight.js/lib/languages/dust.js"),
    "ebnf": () => import("highlight.js/lib/languages/ebnf.js"),
    "elixir": () => import("highlight.js/lib/languages/elixir.js"),
    "elm": () => import("highlight.js/lib/languages/elm.js"),
    "erb": () => import("highlight.js/lib/languages/erb.js"),
    "erlang-repl": () => import("highlight.js/lib/languages/erlang-repl.js"),
    "erlang": () => import("highlight.js/lib/languages/erlang.js"),
    "excel": () => import("highlight.js/lib/languages/excel.js"),
    "fix": () => import("highlight.js/lib/languages/fix.js"),
    "flix": () => import("highlight.js/lib/languages/flix.js"),
    "fortran": () => import("highlight.js/lib/languages/fortran.js"),
    "fsharp": () => import("highlight.js/lib/languages/fsharp.js"),
    "gams": () => import("highlight.js/lib/languages/gams.js"),
    "gauss": () => import("highlight.js/lib/languages/gauss.js"),
    "gcode": () => import("highlight.js/lib/languages/gcode.js"),
    "gherkin": () => import("highlight.js/lib/languages/gherkin.js"),
    "glsl": () => import("highlight.js/lib/languages/glsl.js"),
    "gml": () => import("highlight.js/lib/languages/gml.js"),
    "go": () => import("highlight.js/lib/languages/go.js"),
    "golo": () => import("highlight.js/lib/languages/golo.js"),
    "gradle": () => import("highlight.js/lib/languages/gradle.js"),
    "graphql": () => import("highlight.js/lib/languages/graphql.js"),
    "groovy": () => import("highlight.js/lib/languages/groovy.js"),
    "haml": () => import("highlight.js/lib/languages/haml.js"),
    "handlebars": () => import("highlight.js/lib/languages/handlebars.js"),
    "haskell": () => import("highlight.js/lib/languages/haskell.js"),
    "haxe": () => import("highlight.js/lib/languages/haxe.js"),
    "hsp": () => import("highlight.js/lib/languages/hsp.js"),
    "http": () => import("highlight.js/lib/languages/http.js"),
    "hy": () => import("highlight.js/lib/languages/hy.js"),
    "inform7": () => import("highlight.js/lib/languages/inform7.js"),
    "ini": () => import("highlight.js/lib/languages/ini.js"),
    "irpf90": () => import("highlight.js/lib/languages/irpf90.js"),
    "isbl": () => import("highlight.js/lib/languages/isbl.js"),
    "java": () => import("highlight.js/lib/languages/java.js"),
    "javascript": () => import("highlight.js/lib/languages/javascript.js"),
    "jboss-cli": () => import("highlight.js/lib/languages/jboss-cli.js"),
    "json": () => import("highlight.js/lib/languages/json.js"),
    "julia-repl": () => import("highlight.js/lib/languages/julia-repl.js"),
    "julia": () => import("highlight.js/lib/languages/julia.js"),
    "kotlin": () => import("highlight.js/lib/languages/kotlin.js"),
    "lasso": () => import("highlight.js/lib/languages/lasso.js"),
    "latex": () => import("highlight.js/lib/languages/latex.js"),
    "ldif": () => import("highlight.js/lib/languages/ldif.js"),
    "leaf": () => import("highlight.js/lib/languages/leaf.js"),
    "less": () => import("highlight.js/lib/languages/less.js"),
    "lisp": () => import("highlight.js/lib/languages/lisp.js"),
    "livecodeserver": () => import("highlight.js/lib/languages/livecodeserver.js"),
    "livescript": () => import("highlight.js/lib/languages/livescript.js"),
    "llvm": () => import("highlight.js/lib/languages/llvm.js"),
    "lsl": () => import("highlight.js/lib/languages/lsl.js"),
    "lua": () => import("highlight.js/lib/languages/lua.js"),
    "makefile": () => import("highlight.js/lib/languages/makefile.js"),
    "markdown": () => import("highlight.js/lib/languages/markdown.js"),
    "mathematica": () => import("highlight.js/lib/languages/mathematica.js"),
    "matlab": () => import("highlight.js/lib/languages/matlab.js"),
    "maxima": () => import("highlight.js/lib/languages/maxima.js"),
    "mel": () => import("highlight.js/lib/languages/mel.js"),
    "mercury": () => import("highlight.js/lib/languages/mercury.js"),
    "mipsasm": () => import("highlight.js/lib/languages/mipsasm.js"),
    "mizar": () => import("highlight.js/lib/languages/mizar.js"),
    "mojolicious": () => import("highlight.js/lib/languages/mojolicious.js"),
    "monkey": () => import("highlight.js/lib/languages/monkey.js"),
    "moonscript": () => import("highlight.js/lib/languages/moonscript.js"),
    "n1ql": () => import("highlight.js/lib/languages/n1ql.js"),
    "nestedtext": () => import("highlight.js/lib/languages/nestedtext.js"),
    "nginx": () => import("highlight.js/lib/languages/nginx.js"),
    "nim": () => import("highlight.js/lib/languages/nim.js"),
    "nix": () => import("highlight.js/lib/languages/nix.js"),
    "node-repl": () => import("highlight.js/lib/languages/node-repl.js"),
    "nsis": () => import("highlight.js/lib/languages/nsis.js"),
    "objectivec": () => import("highlight.js/lib/languages/objectivec.js"),
    "ocaml": () => import("highlight.js/lib/languages/ocaml.js"),
    "openscad": () => import("highlight.js/lib/languages/openscad.js"),
    "oxygene": () => import("highlight.js/lib/languages/oxygene.js"),
    "parser3": () => import("highlight.js/lib/languages/parser3.js"),
    "perl": () => import("highlight.js/lib/languages/perl.js"),
    "pf": () => import("highlight.js/lib/languages/pf.js"),
    "pgsql": () => import("highlight.js/lib/languages/pgsql.js"),
    "php-template": () => import("highlight.js/lib/languages/php-template.js"),
    "php": () => import("highlight.js/lib/languages/php.js"),
    "plaintext": () => import("highlight.js/lib/languages/plaintext.js"),
    "pony": () => import("highlight.js/lib/languages/pony.js"),
    "powershell": () => import("highlight.js/lib/languages/powershell.js"),
    "processing": () => import("highlight.js/lib/languages/processing.js"),
    "profile": () => import("highlight.js/lib/languages/profile.js"),
    "prolog": () => import("highlight.js/lib/languages/prolog.js"),
    "properties": () => import("highlight.js/lib/languages/properties.js"),
    "protobuf": () => import("highlight.js/lib/languages/protobuf.js"),
    "puppet": () => import("highlight.js/lib/languages/puppet.js"),
    "purebasic": () => import("highlight.js/lib/languages/purebasic.js"),
    "python-repl": () => import("highlight.js/lib/languages/python-repl.js"),
    "python": () => import("highlight.js/lib/languages/python.js"),
    "q": () => import("highlight.js/lib/languages/q.js"),
    "qml": () => import("highlight.js/lib/languages/qml.js"),
    "r": () => import("highlight.js/lib/languages/r.js"),
    "reasonml": () => import("highlight.js/lib/languages/reasonml.js"),
    "rib": () => import("highlight.js/lib/languages/rib.js"),
    "roboconf": () => import("highlight.js/lib/languages/roboconf.js"),
    "routeros": () => import("highlight.js/lib/languages/routeros.js"),
    "rsl": () => import("highlight.js/lib/languages/rsl.js"),
    "ruby": () => import("highlight.js/lib/languages/ruby.js"),
    "ruleslanguage": () => import("highlight.js/lib/languages/ruleslanguage.js"),
    "rust": () => import("highlight.js/lib/languages/rust.js"),
    "sas": () => import("highlight.js/lib/languages/sas.js"),
    "scala": () => import("highlight.js/lib/languages/scala.js"),
    "scheme": () => import("highlight.js/lib/languages/scheme.js"),
    "scilab": () => import("highlight.js/lib/languages/scilab.js"),
    "scss": () => import("highlight.js/lib/languages/scss.js"),
    "shell": () => import("highlight.js/lib/languages/shell.js"),
    "smali": () => import("highlight.js/lib/languages/smali.js"),
    "smalltalk": () => import("highlight.js/lib/languages/smalltalk.js"),
    "sml": () => import("highlight.js/lib/languages/sml.js"),
    "sqf": () => import("highlight.js/lib/languages/sqf.js"),
    "sql": () => import("highlight.js/lib/languages/sql.js"),
    "stan": () => import("highlight.js/lib/languages/stan.js"),
    "stata": () => import("highlight.js/lib/languages/stata.js"),
    "step21": () => import("highlight.js/lib/languages/step21.js"),
    "stylus": () => import("highlight.js/lib/languages/stylus.js"),
    "subunit": () => import("highlight.js/lib/languages/subunit.js"),
    "swift": () => import("highlight.js/lib/languages/swift.js"),
    "taggerscript": () => import("highlight.js/lib/languages/taggerscript.js"),
    "tap": () => import("highlight.js/lib/languages/tap.js"),
    "tcl": () => import("highlight.js/lib/languages/tcl.js"),
    "thrift": () => import("highlight.js/lib/languages/thrift.js"),
    "tp": () => import("highlight.js/lib/languages/tp.js"),
    "twig": () => import("highlight.js/lib/languages/twig.js"),
    "typescript": () => import("highlight.js/lib/languages/typescript.js"),
    "vala": () => import("highlight.js/lib/languages/vala.js"),
    "vbnet": () => import("highlight.js/lib/languages/vbnet.js"),
    "vbscript-html": () => import("highlight.js/lib/languages/vbscript-html.js"),
    "vbscript": () => import("highlight.js/lib/languages/vbscript.js"),
    "verilog": () => import("highlight.js/lib/languages/verilog.js"),
    "vhdl": () => import("highlight.js/lib/languages/vhdl.js"),
    "vim": () => import("highlight.js/lib/languages/vim.js"),
    "wasm": () => import("highlight.js/lib/languages/wasm.js"),
    "wren": () => import("highlight.js/lib/languages/wren.js"),
    "x86asm": () => import("highlight.js/lib/languages/x86asm.js"),
    "xl": () => import("highlight.js/lib/languages/xl.js"),
    "xml": () => import("highlight.js/lib/languages/xml.js"),
    "xquery": () => import("highlight.js/lib/languages/xquery.js"),
    "yaml": () => import("highlight.js/lib/languages/yaml.js"),
    "zephir": () => import("highlight.js/lib/languages/zephir.js")
}
LANGUAGES["as"] = LANGUAGES["actionscript"];
LANGUAGES["asc"] = LANGUAGES["angelscript"];
LANGUAGES["apacheconf"] = LANGUAGES["apache"];
LANGUAGES["osascript"] = LANGUAGES["applescript"];
LANGUAGES["ino"] = LANGUAGES["arduino"];
LANGUAGES["arm"] = LANGUAGES["armasm"];
LANGUAGES["adoc"] = LANGUAGES["asciidoc"];
LANGUAGES["ahk"] = LANGUAGES["autohotkey"];
LANGUAGES["x++"] = LANGUAGES["axapta"];
LANGUAGES["sh"] = LANGUAGES["bash"];
LANGUAGES["bf"] = LANGUAGES["brainfuck"];
LANGUAGES["h"] = LANGUAGES["c"];
LANGUAGES["capnp"] = LANGUAGES["capnproto"];
LANGUAGES["icl"] = LANGUAGES["dcl"] = LANGUAGES["clean"];
LANGUAGES["clj"] = LANGUAGES["edn"] = LANGUAGES["clojure"];
LANGUAGES["cmake.in"] = LANGUAGES["cmake"];
LANGUAGES["coffee"] = LANGUAGES["cson"] = LANGUAGES["iced"] = LANGUAGES["coffeescript"];
LANGUAGES["cls"] = LANGUAGES["cos"];
LANGUAGES["cc"] = LANGUAGES["c++"] = LANGUAGES["h++"] = LANGUAGES["hpp"] = LANGUAGES["hh"] = LANGUAGES["hxx"] = LANGUAGES["cxx"] = LANGUAGES["cpp"];
LANGUAGES["crm"] = LANGUAGES["pcmk"] = LANGUAGES["crmsh"];
LANGUAGES["cr"] = LANGUAGES["crystal"];
LANGUAGES["cs"] = LANGUAGES["c#"] = LANGUAGES["csharp"];
LANGUAGES["dpr"] = LANGUAGES["dfm"] = LANGUAGES["pas"] = LANGUAGES["pascal"] = LANGUAGES["delphi"];
LANGUAGES["patch"] = LANGUAGES["diff"];
LANGUAGES["jinja"] = LANGUAGES["django"];
LANGUAGES["bind"] = LANGUAGES["zone"] = LANGUAGES["dns"];
LANGUAGES["docker"] = LANGUAGES["dockerfile"];
LANGUAGES["bat"] = LANGUAGES["cmd"] = LANGUAGES["dos"];
LANGUAGES["dst"] = LANGUAGES["dust"];
LANGUAGES["ex"] = LANGUAGES["exs"] = LANGUAGES["elixir"];
LANGUAGES["erl"] = LANGUAGES["erlang"];
LANGUAGES["xlsx"] = LANGUAGES["xls"] = LANGUAGES["excel"];
LANGUAGES["f90"] = LANGUAGES["f95"] = LANGUAGES["fortran"];
LANGUAGES["fs"] = LANGUAGES["f#"] = LANGUAGES["fsharp"];
LANGUAGES["gms"] = LANGUAGES["gams"];
LANGUAGES["gss"] = LANGUAGES["gauss"];
LANGUAGES["nc"] = LANGUAGES["gcode"];
LANGUAGES["feature"] = LANGUAGES["gherkin"];
LANGUAGES["golang"] = LANGUAGES["go"];
LANGUAGES["gql"] = LANGUAGES["graphql"];
LANGUAGES["hbs"] = LANGUAGES["html.hbs"] = LANGUAGES["html.handlebars"] = LANGUAGES["htmlbars"] = LANGUAGES["handlebars"];
LANGUAGES["hs"] = LANGUAGES["haskell"];
LANGUAGES["hx"] = LANGUAGES["haxe"];
LANGUAGES["https"] = LANGUAGES["http"];
LANGUAGES["hylang"] = LANGUAGES["hy"];
LANGUAGES["i7"] = LANGUAGES["inform7"];
LANGUAGES["toml"] = LANGUAGES["ini"];
LANGUAGES["jsp"] = LANGUAGES["java"];
LANGUAGES["js"] = LANGUAGES["jsx"] = LANGUAGES["mjs"] = LANGUAGES["cjs"] = LANGUAGES["javascript"];
LANGUAGES["wildfly-cli"] = LANGUAGES["jboss-cli"];
LANGUAGES["jldoctest"] = LANGUAGES["julia-repl"];
LANGUAGES["kt"] = LANGUAGES["kts"] = LANGUAGES["kotlin"];
LANGUAGES["ls"] = LANGUAGES["lassoscript"] = LANGUAGES["lasso"];
LANGUAGES["tex"] = LANGUAGES["latex"];
LANGUAGES["ls"] = LANGUAGES["livescript"];
LANGUAGES["mk"] = LANGUAGES["mak"] = LANGUAGES["make"] = LANGUAGES["makefile"];
LANGUAGES["md"] = LANGUAGES["mkdown"] = LANGUAGES["mkd"] = LANGUAGES["markdown"];
LANGUAGES["mma"] = LANGUAGES["wl"] = LANGUAGES["mathematica"];
LANGUAGES["m"] = LANGUAGES["moo"] = LANGUAGES["mercury"];
LANGUAGES["mips"] = LANGUAGES["mipsasm"];
LANGUAGES["moon"] = LANGUAGES["moonscript"];
LANGUAGES["nt"] = LANGUAGES["nestedtext"];
LANGUAGES["nginxconf"] = LANGUAGES["nginx"];
LANGUAGES["nixos"] = LANGUAGES["nix"];
LANGUAGES["mm"] = LANGUAGES["objc"] = LANGUAGES["obj-c"] = LANGUAGES["obj-c++"] = LANGUAGES["objective-c++"] = LANGUAGES["objectivec"];
LANGUAGES["ml"] = LANGUAGES["ocaml"];
LANGUAGES["scad"] = LANGUAGES["openscad"];
LANGUAGES["pl"] = LANGUAGES["pm"] = LANGUAGES["perl"];
LANGUAGES["pf.conf"] = LANGUAGES["pf"];
LANGUAGES["postgres"] = LANGUAGES["postgresql"] = LANGUAGES["pgsql"];
LANGUAGES["text"] = LANGUAGES["txt"] = LANGUAGES["plaintext"];
LANGUAGES["pwsh"] = LANGUAGES["ps"] = LANGUAGES["ps1"] = LANGUAGES["powershell"];
LANGUAGES["pde"] = LANGUAGES["processing"];
LANGUAGES["pp"] = LANGUAGES["puppet"];
LANGUAGES["pb"] = LANGUAGES["pbi"] = LANGUAGES["purebasic"];
LANGUAGES["pycon"] = LANGUAGES["python-repl"];
LANGUAGES["py"] = LANGUAGES["gyp"] = LANGUAGES["ipython"] = LANGUAGES["python"];
LANGUAGES["k"] = LANGUAGES["kdb"] = LANGUAGES["q"];
LANGUAGES["qt"] = LANGUAGES["qml"];
LANGUAGES["re"] = LANGUAGES["reasonml"];
LANGUAGES["graph"] = LANGUAGES["instances"] = LANGUAGES["roboconf"];
LANGUAGES["mikrotik"] = LANGUAGES["routeros"];
LANGUAGES["rb"] = LANGUAGES["gemspec"] = LANGUAGES["podspec"] = LANGUAGES["thor"] = LANGUAGES["irb"] = LANGUAGES["ruby"];
LANGUAGES["rs"] = LANGUAGES["rust"];
LANGUAGES["sci"] = LANGUAGES["scilab"];
LANGUAGES["console"] = LANGUAGES["shellsession"] = LANGUAGES["shell"];
LANGUAGES["st"] = LANGUAGES["smalltalk"];
LANGUAGES["ml"] = LANGUAGES["sml"];
LANGUAGES["stanfuncs"] = LANGUAGES["stan"];
LANGUAGES["do"] = LANGUAGES["ado"] = LANGUAGES["stata"];
LANGUAGES["p21"] = LANGUAGES["step"] = LANGUAGES["stp"] = LANGUAGES["step21"];
LANGUAGES["styl"] = LANGUAGES["stylus"];
LANGUAGES["tk"] = LANGUAGES["tcl"];
LANGUAGES["craftcms"] = LANGUAGES["twig"];
LANGUAGES["ts"] = LANGUAGES["tsx"] = LANGUAGES["typescript"];
LANGUAGES["vb"] = LANGUAGES["vbnet"];
LANGUAGES["vbs"] = LANGUAGES["vbscript"];
LANGUAGES["v"] = LANGUAGES["sv"] = LANGUAGES["svh"] = LANGUAGES["verilog"];
LANGUAGES["tao"] = LANGUAGES["xl"];
LANGUAGES["html"] = LANGUAGES["xhtml"] = LANGUAGES["rss"] = LANGUAGES["atom"] = LANGUAGES["xjb"] = LANGUAGES["xsd"] = LANGUAGES["xsl"] = LANGUAGES["plist"] = LANGUAGES["wsf"] = LANGUAGES["svg"] = LANGUAGES["xml"];
LANGUAGES["xpath"] = LANGUAGES["xq"] = LANGUAGES["xquery"];
LANGUAGES["yml"] = LANGUAGES["yaml"];
LANGUAGES["zep"] = LANGUAGES["zephir"];
