import { createSignal, Show } from 'solid-js';

import "./code.scss";

import hljs from "highlight.js/lib/core";

export interface ICodeProps {
    src: string,
    language?: string,
}

function hasLang(lang: string | null | undefined | void): string | undefined {
    if(lang && hljs.getLanguage(lang)) {
        return lang;
    }
    return;
}

export default function Code(props: ICodeProps) {
    let pending_language = props.language,
        has_language = pending_language && !!hljs.getLanguage(pending_language),
        language: () => string | null | undefined | void = () => has_language ? pending_language : null,
        loader;

    if(pending_language && !has_language && (loader = LANGUAGES[pending_language])) {
        let [lang, setLang] = createSignal<string>();
        language = lang; // setup signal to trigger refresh

        // resolve alias
        if(typeof loader === 'string') {
            pending_language = loader;
            loader = LANGUAGES[loader] as LanguageLoader;
        }

        loader().then(l => {
            // avoid re-registering if multiple code components rendered at the same time
            if(!hljs.getLanguage(pending_language!)) {
                hljs.registerLanguage(pending_language!, l.default);
            }
            setLang(pending_language);
        });
    }

    return (
        <Show when={hasLang(language())} keyed fallback={
            <pre class="hljs">
                <code textContent={/* @once */props.src.trim()} />
            </pre>
        }>
            {language => {
                let compiled = hljs.highlight(props.src, { language });

                return (
                    <pre class="hljs" data-language={/*@once*/compiled.language}>
                        <code innerHTML={/* @once */compiled.value} />
                    </pre>
                );
            }}
        </Show>
    );
}

import type { LanguageFn } from 'highlight.js';

type LanguageLoader = () => Promise<{ default: LanguageFn }>;

// == AUTOGENERATED BELOW THIS LINE ==
const LANGUAGES: { [language: string]: string | LanguageLoader } = {
    "1c": () => import("highlight.js/lib/languages/1c"),
    "abnf": () => import("highlight.js/lib/languages/abnf"),
    "accesslog": () => import("highlight.js/lib/languages/accesslog"),
    "actionscript": () => import("highlight.js/lib/languages/actionscript"),
    "ada": () => import("highlight.js/lib/languages/ada"),
    "angelscript": () => import("highlight.js/lib/languages/angelscript"),
    "apache": () => import("highlight.js/lib/languages/apache"),
    "applescript": () => import("highlight.js/lib/languages/applescript"),
    "arcade": () => import("highlight.js/lib/languages/arcade"),
    "arduino": () => import("highlight.js/lib/languages/arduino"),
    "armasm": () => import("highlight.js/lib/languages/armasm"),
    "asciidoc": () => import("highlight.js/lib/languages/asciidoc"),
    "aspectj": () => import("highlight.js/lib/languages/aspectj"),
    "autohotkey": () => import("highlight.js/lib/languages/autohotkey"),
    "autoit": () => import("highlight.js/lib/languages/autoit"),
    "avrasm": () => import("highlight.js/lib/languages/avrasm"),
    "awk": () => import("highlight.js/lib/languages/awk"),
    "axapta": () => import("highlight.js/lib/languages/axapta"),
    "bash": () => import("highlight.js/lib/languages/bash"),
    "basic": () => import("highlight.js/lib/languages/basic"),
    "bnf": () => import("highlight.js/lib/languages/bnf"),
    "brainfuck": () => import("highlight.js/lib/languages/brainfuck"),
    "c": () => import("highlight.js/lib/languages/c"),
    "cal": () => import("highlight.js/lib/languages/cal"),
    "capnproto": () => import("highlight.js/lib/languages/capnproto"),
    "ceylon": () => import("highlight.js/lib/languages/ceylon"),
    "clean": () => import("highlight.js/lib/languages/clean"),
    "clojure-repl": () => import("highlight.js/lib/languages/clojure-repl"),
    "clojure": () => import("highlight.js/lib/languages/clojure"),
    "cmake": () => import("highlight.js/lib/languages/cmake"),
    "coffeescript": () => import("highlight.js/lib/languages/coffeescript"),
    "coq": () => import("highlight.js/lib/languages/coq"),
    "cos": () => import("highlight.js/lib/languages/cos"),
    "cpp": () => import("highlight.js/lib/languages/cpp"),
    "crmsh": () => import("highlight.js/lib/languages/crmsh"),
    "crystal": () => import("highlight.js/lib/languages/crystal"),
    "csharp": () => import("highlight.js/lib/languages/csharp"),
    "csp": () => import("highlight.js/lib/languages/csp"),
    "css": () => import("highlight.js/lib/languages/css"),
    "d": () => import("highlight.js/lib/languages/d"),
    "dart": () => import("highlight.js/lib/languages/dart"),
    "delphi": () => import("highlight.js/lib/languages/delphi"),
    "diff": () => import("highlight.js/lib/languages/diff"),
    "django": () => import("highlight.js/lib/languages/django"),
    "dns": () => import("highlight.js/lib/languages/dns"),
    "dockerfile": () => import("highlight.js/lib/languages/dockerfile"),
    "dos": () => import("highlight.js/lib/languages/dos"),
    "dsconfig": () => import("highlight.js/lib/languages/dsconfig"),
    "dts": () => import("highlight.js/lib/languages/dts"),
    "dust": () => import("highlight.js/lib/languages/dust"),
    "ebnf": () => import("highlight.js/lib/languages/ebnf"),
    "elixir": () => import("highlight.js/lib/languages/elixir"),
    "elm": () => import("highlight.js/lib/languages/elm"),
    "erb": () => import("highlight.js/lib/languages/erb"),
    "erlang-repl": () => import("highlight.js/lib/languages/erlang-repl"),
    "erlang": () => import("highlight.js/lib/languages/erlang"),
    "excel": () => import("highlight.js/lib/languages/excel"),
    "fix": () => import("highlight.js/lib/languages/fix"),
    "flix": () => import("highlight.js/lib/languages/flix"),
    "fortran": () => import("highlight.js/lib/languages/fortran"),
    "fsharp": () => import("highlight.js/lib/languages/fsharp"),
    "gams": () => import("highlight.js/lib/languages/gams"),
    "gauss": () => import("highlight.js/lib/languages/gauss"),
    "gcode": () => import("highlight.js/lib/languages/gcode"),
    "gherkin": () => import("highlight.js/lib/languages/gherkin"),
    "glsl": () => import("highlight.js/lib/languages/glsl"),
    "gml": () => import("highlight.js/lib/languages/gml"),
    "go": () => import("highlight.js/lib/languages/go"),
    "golo": () => import("highlight.js/lib/languages/golo"),
    "gradle": () => import("highlight.js/lib/languages/gradle"),
    "graphql": () => import("highlight.js/lib/languages/graphql"),
    "groovy": () => import("highlight.js/lib/languages/groovy"),
    "haml": () => import("highlight.js/lib/languages/haml"),
    "handlebars": () => import("highlight.js/lib/languages/handlebars"),
    "haskell": () => import("highlight.js/lib/languages/haskell"),
    "haxe": () => import("highlight.js/lib/languages/haxe"),
    "hsp": () => import("highlight.js/lib/languages/hsp"),
    "http": () => import("highlight.js/lib/languages/http"),
    "hy": () => import("highlight.js/lib/languages/hy"),
    "inform7": () => import("highlight.js/lib/languages/inform7"),
    "ini": () => import("highlight.js/lib/languages/ini"),
    "irpf90": () => import("highlight.js/lib/languages/irpf90"),
    "isbl": () => import("highlight.js/lib/languages/isbl"),
    "java": () => import("highlight.js/lib/languages/java"),
    "javascript": () => import("highlight.js/lib/languages/javascript"),
    "jboss-cli": () => import("highlight.js/lib/languages/jboss-cli"),
    "json": () => import("highlight.js/lib/languages/json"),
    "julia-repl": () => import("highlight.js/lib/languages/julia-repl"),
    "julia": () => import("highlight.js/lib/languages/julia"),
    "kotlin": () => import("highlight.js/lib/languages/kotlin"),
    "lasso": () => import("highlight.js/lib/languages/lasso"),
    "latex": () => import("highlight.js/lib/languages/latex"),
    "ldif": () => import("highlight.js/lib/languages/ldif"),
    "leaf": () => import("highlight.js/lib/languages/leaf"),
    "less": () => import("highlight.js/lib/languages/less"),
    "lisp": () => import("highlight.js/lib/languages/lisp"),
    "livecodeserver": () => import("highlight.js/lib/languages/livecodeserver"),
    "livescript": () => import("highlight.js/lib/languages/livescript"),
    "llvm": () => import("highlight.js/lib/languages/llvm"),
    "lsl": () => import("highlight.js/lib/languages/lsl"),
    "lua": () => import("highlight.js/lib/languages/lua"),
    "makefile": () => import("highlight.js/lib/languages/makefile"),
    "markdown": () => import("highlight.js/lib/languages/markdown"),
    "mathematica": () => import("highlight.js/lib/languages/mathematica"),
    "matlab": () => import("highlight.js/lib/languages/matlab"),
    "maxima": () => import("highlight.js/lib/languages/maxima"),
    "mel": () => import("highlight.js/lib/languages/mel"),
    "mercury": () => import("highlight.js/lib/languages/mercury"),
    "mipsasm": () => import("highlight.js/lib/languages/mipsasm"),
    "mizar": () => import("highlight.js/lib/languages/mizar"),
    "mojolicious": () => import("highlight.js/lib/languages/mojolicious"),
    "monkey": () => import("highlight.js/lib/languages/monkey"),
    "moonscript": () => import("highlight.js/lib/languages/moonscript"),
    "n1ql": () => import("highlight.js/lib/languages/n1ql"),
    "nestedtext": () => import("highlight.js/lib/languages/nestedtext"),
    "nginx": () => import("highlight.js/lib/languages/nginx"),
    "nim": () => import("highlight.js/lib/languages/nim"),
    "nix": () => import("highlight.js/lib/languages/nix"),
    "node-repl": () => import("highlight.js/lib/languages/node-repl"),
    "nsis": () => import("highlight.js/lib/languages/nsis"),
    "objectivec": () => import("highlight.js/lib/languages/objectivec"),
    "ocaml": () => import("highlight.js/lib/languages/ocaml"),
    "openscad": () => import("highlight.js/lib/languages/openscad"),
    "oxygene": () => import("highlight.js/lib/languages/oxygene"),
    "parser3": () => import("highlight.js/lib/languages/parser3"),
    "perl": () => import("highlight.js/lib/languages/perl"),
    "pf": () => import("highlight.js/lib/languages/pf"),
    "pgsql": () => import("highlight.js/lib/languages/pgsql"),
    "php-template": () => import("highlight.js/lib/languages/php-template"),
    "php": () => import("highlight.js/lib/languages/php"),
    "plaintext": () => import("highlight.js/lib/languages/plaintext"),
    "pony": () => import("highlight.js/lib/languages/pony"),
    "powershell": () => import("highlight.js/lib/languages/powershell"),
    "processing": () => import("highlight.js/lib/languages/processing"),
    "profile": () => import("highlight.js/lib/languages/profile"),
    "prolog": () => import("highlight.js/lib/languages/prolog"),
    "properties": () => import("highlight.js/lib/languages/properties"),
    "protobuf": () => import("highlight.js/lib/languages/protobuf"),
    "puppet": () => import("highlight.js/lib/languages/puppet"),
    "purebasic": () => import("highlight.js/lib/languages/purebasic"),
    "python-repl": () => import("highlight.js/lib/languages/python-repl"),
    "python": () => import("highlight.js/lib/languages/python"),
    "q": () => import("highlight.js/lib/languages/q"),
    "qml": () => import("highlight.js/lib/languages/qml"),
    "r": () => import("highlight.js/lib/languages/r"),
    "reasonml": () => import("highlight.js/lib/languages/reasonml"),
    "rib": () => import("highlight.js/lib/languages/rib"),
    "roboconf": () => import("highlight.js/lib/languages/roboconf"),
    "routeros": () => import("highlight.js/lib/languages/routeros"),
    "rsl": () => import("highlight.js/lib/languages/rsl"),
    "ruby": () => import("highlight.js/lib/languages/ruby"),
    "ruleslanguage": () => import("highlight.js/lib/languages/ruleslanguage"),
    "rust": () => import("highlight.js/lib/languages/rust"),
    "sas": () => import("highlight.js/lib/languages/sas"),
    "scala": () => import("highlight.js/lib/languages/scala"),
    "scheme": () => import("highlight.js/lib/languages/scheme"),
    "scilab": () => import("highlight.js/lib/languages/scilab"),
    "scss": () => import("highlight.js/lib/languages/scss"),
    "shell": () => import("highlight.js/lib/languages/shell"),
    "smali": () => import("highlight.js/lib/languages/smali"),
    "smalltalk": () => import("highlight.js/lib/languages/smalltalk"),
    "sml": () => import("highlight.js/lib/languages/sml"),
    "sqf": () => import("highlight.js/lib/languages/sqf"),
    "sql": () => import("highlight.js/lib/languages/sql"),
    "stan": () => import("highlight.js/lib/languages/stan"),
    "stata": () => import("highlight.js/lib/languages/stata"),
    "step21": () => import("highlight.js/lib/languages/step21"),
    "stylus": () => import("highlight.js/lib/languages/stylus"),
    "subunit": () => import("highlight.js/lib/languages/subunit"),
    "swift": () => import("highlight.js/lib/languages/swift"),
    "taggerscript": () => import("highlight.js/lib/languages/taggerscript"),
    "tap": () => import("highlight.js/lib/languages/tap"),
    "tcl": () => import("highlight.js/lib/languages/tcl"),
    "thrift": () => import("highlight.js/lib/languages/thrift"),
    "tp": () => import("highlight.js/lib/languages/tp"),
    "twig": () => import("highlight.js/lib/languages/twig"),
    "typescript": () => import("highlight.js/lib/languages/typescript"),
    "vala": () => import("highlight.js/lib/languages/vala"),
    "vbnet": () => import("highlight.js/lib/languages/vbnet"),
    "vbscript-html": () => import("highlight.js/lib/languages/vbscript-html"),
    "vbscript": () => import("highlight.js/lib/languages/vbscript"),
    "verilog": () => import("highlight.js/lib/languages/verilog"),
    "vhdl": () => import("highlight.js/lib/languages/vhdl"),
    "vim": () => import("highlight.js/lib/languages/vim"),
    "wasm": () => import("highlight.js/lib/languages/wasm"),
    "wren": () => import("highlight.js/lib/languages/wren"),
    "x86asm": () => import("highlight.js/lib/languages/x86asm"),
    "xl": () => import("highlight.js/lib/languages/xl"),
    "xml": () => import("highlight.js/lib/languages/xml"),
    "xquery": () => import("highlight.js/lib/languages/xquery"),
    "yaml": () => import("highlight.js/lib/languages/yaml"),
    "zephir": () => import("highlight.js/lib/languages/zephir"),
    "as": "actionscript",
    "asc": "angelscript",
    "apacheconf": "apache",
    "osascript": "applescript",
    "ino": "arduino",
    "arm": "armasm",
    "adoc": "asciidoc",
    "ahk": "autohotkey",
    "x++": "axapta",
    "sh": "bash",
    "bf": "brainfuck",
    "h": "c",
    "capnp": "capnproto",
    "cmake.in": "cmake",
    "cls": "cos",
    "cr": "crystal",
    "patch": "diff",
    "jinja": "django",
    "docker": "dockerfile",
    "dst": "dust",
    "erl": "erlang",
    "gms": "gams",
    "gss": "gauss",
    "nc": "gcode",
    "feature": "gherkin",
    "golang": "go",
    "gql": "graphql",
    "hs": "haskell",
    "hx": "haxe",
    "https": "http",
    "hylang": "hy",
    "i7": "inform7",
    "toml": "ini",
    "jsp": "java",
    "wildfly-cli": "jboss-cli",
    "jldoctest": "julia-repl",
    "tex": "latex",
    "mips": "mipsasm",
    "moon": "moonscript",
    "nt": "nestedtext",
    "nginxconf": "nginx",
    "nixos": "nix",
    "ml": "ocaml",
    "scad": "openscad",
    "pf.conf": "pf",
    "pde": "processing",
    "pp": "puppet",
    "pycon": "python-repl",
    "qt": "qml",
    "re": "reasonml",
    "mikrotik": "routeros",
    "rs": "rust",
    "sci": "scilab",
    "st": "smalltalk",
    "stanfuncs": "stan",
    "styl": "stylus",
    "tk": "tcl",
    "craftcms": "twig",
    "vb": "vbnet",
    "vbs": "vbscript",
    "tao": "xl",
    "yml": "yaml",
    "zep": "zephir",
}
LANGUAGES["icl"] = LANGUAGES["dcl"] = "clean";
LANGUAGES["clj"] = LANGUAGES["edn"] = "clojure";
LANGUAGES["coffee"] = LANGUAGES["cson"] = LANGUAGES["iced"] = "coffeescript";
LANGUAGES["cc"] = LANGUAGES["c++"] = LANGUAGES["h++"] = LANGUAGES["hpp"] = LANGUAGES["hh"] = LANGUAGES["hxx"] = LANGUAGES["cxx"] = "cpp";
LANGUAGES["crm"] = LANGUAGES["pcmk"] = "crmsh";
LANGUAGES["cs"] = LANGUAGES["c#"] = "csharp";
LANGUAGES["dpr"] = LANGUAGES["dfm"] = LANGUAGES["pas"] = LANGUAGES["pascal"] = "delphi";
LANGUAGES["bind"] = LANGUAGES["zone"] = "dns";
LANGUAGES["bat"] = LANGUAGES["cmd"] = "dos";
LANGUAGES["ex"] = LANGUAGES["exs"] = "elixir";
LANGUAGES["xlsx"] = LANGUAGES["xls"] = "excel";
LANGUAGES["f90"] = LANGUAGES["f95"] = "fortran";
LANGUAGES["fs"] = LANGUAGES["f#"] = "fsharp";
LANGUAGES["hbs"] = LANGUAGES["html.hbs"] = LANGUAGES["html.handlebars"] = LANGUAGES["htmlbars"] = "handlebars";
LANGUAGES["js"] = LANGUAGES["jsx"] = LANGUAGES["mjs"] = LANGUAGES["cjs"] = "javascript";
LANGUAGES["kt"] = LANGUAGES["kts"] = "kotlin";
LANGUAGES["ls"] = LANGUAGES["lassoscript"] = "lasso";
LANGUAGES["mk"] = LANGUAGES["mak"] = LANGUAGES["make"] = "makefile";
LANGUAGES["md"] = LANGUAGES["mkdown"] = LANGUAGES["mkd"] = "markdown";
LANGUAGES["mma"] = LANGUAGES["wl"] = "mathematica";
LANGUAGES["m"] = LANGUAGES["moo"] = "mercury";
LANGUAGES["mm"] = LANGUAGES["objc"] = LANGUAGES["obj-c"] = LANGUAGES["obj-c++"] = LANGUAGES["objective-c++"] = "objectivec";
LANGUAGES["pl"] = LANGUAGES["pm"] = "perl";
LANGUAGES["postgres"] = LANGUAGES["postgresql"] = "pgsql";
LANGUAGES["text"] = LANGUAGES["txt"] = "plaintext";
LANGUAGES["pwsh"] = LANGUAGES["ps"] = LANGUAGES["ps1"] = "powershell";
LANGUAGES["pb"] = LANGUAGES["pbi"] = "purebasic";
LANGUAGES["py"] = LANGUAGES["gyp"] = LANGUAGES["ipython"] = "python";
LANGUAGES["k"] = LANGUAGES["kdb"] = "q";
LANGUAGES["graph"] = LANGUAGES["instances"] = "roboconf";
LANGUAGES["rb"] = LANGUAGES["gemspec"] = LANGUAGES["podspec"] = LANGUAGES["thor"] = LANGUAGES["irb"] = "ruby";
LANGUAGES["console"] = LANGUAGES["shellsession"] = "shell";
LANGUAGES["do"] = LANGUAGES["ado"] = "stata";
LANGUAGES["p21"] = LANGUAGES["step"] = LANGUAGES["stp"] = "step21";
LANGUAGES["ts"] = LANGUAGES["tsx"] = "typescript";
LANGUAGES["v"] = LANGUAGES["sv"] = LANGUAGES["svh"] = "verilog";
LANGUAGES["html"] = LANGUAGES["xhtml"] = LANGUAGES["rss"] = LANGUAGES["atom"] = LANGUAGES["xjb"] = LANGUAGES["xsd"] = LANGUAGES["xsl"] = LANGUAGES["plist"] = LANGUAGES["wsf"] = LANGUAGES["svg"] = "xml";
LANGUAGES["xpath"] = LANGUAGES["xq"] = "xquery";
