// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import en from './en'
import es from './es'
import owo from './owo'

import en_main from './en/main'
import es_main from './es/main'
import owo_main from './owo/main'

const localeTranslations = {
	en: {
		...en,
		main: en_main
	},
	es: {
		...es,
		main: es_main
	},
	owo: {
		...owo,
		main: owo_main
	},
}

export const loadLocale = (locale: Locales) => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = () => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales) => {
	loadedFormatters[locale] = initFormatters(locale)
}
