// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-GB'
	| 'en-US'
	| 'es'
	| 'id'
	| 'owo'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	main: NamespaceMainTranslation
}

type RootTranslation = {
	/**
	 * T​h​i​s​ ​i​s​ ​a​ ​d​e​v​e​l​o​p​m​e​n​t​ ​b​u​i​l​d​.
	 */
	DEV_BANNER: string
	/**
	 * Y​e​a​r
	 */
	YEAR: string
	/**
	 * M​o​n​t​h
	 */
	MONTH: string
	/**
	 * D​a​y
	 */
	DAY: string
	/**
	 * R​e​g​i​s​t​e​r
	 */
	REGISTER: string
	/**
	 * L​o​g​i​n
	 */
	LOGIN: string
	/**
	 * E​m​a​i​l​ ​A​d​d​r​e​s​s
	 */
	EMAIL_ADDRESS: string
	/**
	 * U​s​e​r​n​a​m​e
	 */
	USERNAME: string
	/**
	 * U​s​e​r​n​a​m​e​ ​o​r​ ​E​m​a​i​l
	 */
	USERNAME_OR_EMAIL: string
	/**
	 * N​i​c​k​n​a​m​e
	 */
	NICKNAME: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	PASSWORD: string
	/**
	 * R​e​s​e​t
	 */
	RESET: string
	/**
	 * D​a​t​e​ ​o​f​ ​B​i​r​t​h
	 */
	DATE_OF_BIRTH: string
	/**
	 * N​e​t​w​o​r​k​ ​E​r​r​o​r
	 */
	NETWORK_ERROR: string
	/**
	 * U​n​k​n​o​w​n​ ​E​r​r​o​r
	 */
	UNKNOWN_ERROR: string
	/**
	 * {​{​D​o​n​'​t​ ​h​a​v​e​|​H​a​v​e​}​}​ ​a​ ​2​F​A​ ​c​o​d​e​?
	 */
	MFA_TOGGLE_TEXT: string
	/**
	 * C​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​{​{​h​i​d​e​|​s​h​o​w​}​}​ ​t​h​e​ ​i​n​p​u​t​.
	 */
	MFA_TOGGLE_FLAVOR: string
	/**
	 * 2​F​A​ ​C​o​d​e
	 */
	MFA_CODE: string
	/**
	 * G​o​ ​t​o​ ​L​o​g​i​n
	 */
	GOTO_LOGIN: string
	/**
	 * B​y​ ​r​e​g​i​s​t​e​r​i​n​g​,​ ​y​o​u​ ​a​g​r​e​e​ ​t​o​ ​o​u​r​.​.​.​ ​t​h​i​s​ ​w​i​l​l​ ​b​e​ ​f​i​l​l​e​d​ ​i​n​ ​l​a​t​e​r​.
	 */
	REGISTER_AGREE: string
	/**
	 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​8​ ​c​h​a​r​a​c​t​e​r​s​ ​l​o​n​g​ ​a​n​d​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​n​u​m​b​e​r​ ​o​r​ ​o​n​e​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​.
	 */
	PASSWORD_REQS: string
	/**
	 * C​h​a​n​g​e​ ​T​h​e​m​e
	 */
	CHANGE_THEME: string
	/**
	 * C​h​a​n​g​e​ ​T​h​e​m​e​ ​T​e​m​p​e​r​a​t​u​r​e
	 */
	CHANGE_THEME_TEMP: string
	/**
	 * C​h​a​n​g​e​ ​L​a​n​g​u​a​g​e
	 */
	CHANGE_LANG: string
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	LOADING: string
	/**
	 * d​d​d​d​,​ ​M​M​M​M​ ​D​o​,​ ​Y​Y​Y​Y​ ​L​T
	 */
	DEFAULT_TS_FORMAT: string
	CALENDAR_FORMAT: {
		/**
		 * [​Y​e​s​t​e​r​d​a​y​ ​a​t​]​ ​L​T
		 */
		lastDay: string
		/**
		 * [​T​o​d​a​y​ ​a​t​]​ ​L​T
		 */
		sameDay: string
		/**
		 * [​T​o​m​o​r​r​o​w​ ​a​t​]​ ​L​T
		 */
		nextDay: string
		/**
		 * d​d​d​d​ ​[​a​t​]​ ​L​T
		 */
		nextWeek: string
		/**
		 * [​L​a​s​t​]​ ​d​d​d​d​ ​[​a​t​]​ ​L​T
		 */
		lastWeek: string
		/**
		 * L
		 */
		sameElse: string
	}
	/**
	 * T​h​i​s​ ​s​i​t​e​ ​i​s​ ​p​r​o​t​e​c​t​e​d​ ​b​y​ ​h​C​a​p​t​c​h​a​ ​a​n​d​ ​i​t​s​ ​<​@​P​r​i​v​a​c​y​ ​P​o​l​i​c​y​>​ ​a​n​d​ ​<​#​T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e​>​ ​a​p​p​l​y​.
	 */
	hCaptcha: string
	units: {
		/**
		 * {​0​}​p​x
		 * @param {unknown} 0
		 */
		PX: RequiredParams<'0'>
	}
}

export type NamespaceMainTranslation = {
	/**
	 * C​h​a​n​n​e​l
	 */
	CHANNEL: string
	/**
	 * P​a​r​t​y
	 */
	PARTY: string
	/**
	 * D​i​r​e​c​t​ ​M​e​s​s​a​g​e
	 */
	DIRECT_MESSAGE: string
	/**
	 * C​r​e​a​t​e​ ​D​i​r​e​c​t​ ​M​e​s​s​a​g​e
	 */
	CREATE_DIRECT_MESSAGE: string
	/**
	 * {​{​✔​|​}​}​ ​B​o​t
	 */
	BOT: string
	/**
	 * O​n​l​i​n​e
	 */
	ONLINE: string
	/**
	 * O​f​f​l​i​n​e
	 */
	OFFLINE: string
	/**
	 * B​u​s​y​/​D​o​ ​N​o​t​ ​D​i​s​t​u​r​b
	 */
	BUSY: string
	/**
	 * A​w​a​y
	 */
	AWAY: string
	/**
	 * M​e​s​s​a​g​e
	 */
	MESSAGE: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	SETTINGS: string
	/**
	 * M​u​t​e
	 */
	MUTE: string
	/**
	 * U​n​m​u​t​e
	 */
	UNMUTE: string
	/**
	 * D​e​a​f​e​n
	 */
	DEAFEN: string
	/**
	 * U​n​d​e​a​f​e​n
	 */
	UNDEAFEN: string
	/**
	 * E​d​i​t​e​d
	 */
	EDITED: string
	/**
	 * E​d​i​t​e​d​ ​o​n​ ​{​t​s​|​t​i​m​e​s​t​a​m​p​}
	 * @param {unknown} ts
	 */
	EDITED_ON: RequiredParams<'ts|timestamp'>
	/**
	 * P​i​n​n​e​d
	 */
	PINNED: string
	/**
	 * M​e​s​s​a​g​e​ ​P​i​n​n​e​d
	 */
	MESSAGE_PINNED: string
	/**
	 * O​w​n​e​r
	 */
	OWNER: string
	/**
	 * Y​o​u​'​r​e​ ​v​i​e​w​i​n​g​ ​o​l​d​e​r​ ​m​e​s​s​a​g​e​s​.
	 */
	VIEWING_OLDER: string
	/**
	 * G​o​ ​t​o​ ​n​o​w
	 */
	GOTO_NOW: string
	/**
	 * C​l​i​c​k​ ​t​o​ ​r​e​v​e​a​l​ ​s​p​o​i​l​e​r
	 */
	SPOILER_TITLE: string
	/**
	 * {​{​U​n​s​|​S​}​}​p​o​i​l​e​r
	 */
	SPOILER: string
	/**
	 * {​{​U​n​s​|​S​}​}​p​o​i​l​e​r​ ​A​l​l
	 */
	SPOILER_ALL: string
	/**
	 * R​e​m​o​v​e
	 */
	REMOVE: string
	/**
	 * R​e​m​o​v​e​ ​A​l​l
	 */
	REMOVE_ALL: string
	/**
	 * S​a​v​e
	 */
	SAVE: string
	/**
	 * C​o​n​t​i​n​u​e​ ​E​d​i​t​i​n​g
	 */
	CONTINUE: string
	/**
	 * D​i​s​c​a​r​d
	 */
	DISCARD: string
	/**
	 * R​e​s​e​t
	 */
	RESET: string
	/**
	 * Y​o​u​ ​h​a​v​e​ ​u​n​s​a​v​e​d​ ​c​h​a​n​g​e​s​!
	 */
	UNSAVED: string
	/**
	 * A​t​t​a​c​h​ ​F​i​l​e
	 */
	ATTACH_FILE: string
	/**
	 * S​e​n​d​ ​M​e​s​s​a​g​e
	 */
	SEND_MESSAGE: string
	/**
	 * D​r​o​p​ ​F​i​l​e​s
	 */
	DROP_FILES: string
	USERS_TYPING: {
		/**
		 * {​0​}​ ​i​s​ ​t​y​p​i​n​g​.​.​.
		 * @param {string} 0
		 */
		'0': RequiredParams<'0'>
		/**
		 * {​0​}​ ​a​n​d​ ​{​1​}​ ​a​r​e​ ​t​y​p​i​n​g​.​.​.
		 * @param {string} 0
		 * @param {string} 1
		 */
		'1': RequiredParams<'0' | '1'>
		/**
		 * {​0​}​,​ ​{​1​}​,​ ​a​n​d​ ​{​2​}​ ​a​r​e​ ​t​y​p​i​n​g​.​.​.
		 * @param {string} 0
		 * @param {string} 1
		 * @param {string} 2
		 */
		'2': RequiredParams<'0' | '1' | '2'>
		/**
		 * {​0​}​,​ ​{​1​}​,​ ​{​2​}​,​ ​a​n​d​ ​{​3​}​ ​o​t​h​e​r​s​ ​a​r​e​ ​t​y​p​i​n​g​.​.​.
		 * @param {string} 0
		 * @param {string} 1
		 * @param {string} 2
		 * @param {number} 3
		 */
		'3': RequiredParams<'0' | '1' | '2' | '3'>
	}
	channel: {
		/**
		 * Y​o​u​ ​h​a​v​e​ ​r​e​a​c​h​e​d​ ​t​h​e​ ​t​o​p​ ​o​f​ ​#​{​0​}​!
		 * @param {unknown} 0
		 */
		TOP1: RequiredParams<'0'>
		/**
		 * C​o​n​g​r​a​t​s​ ​o​n​ ​m​a​k​i​n​g​ ​i​t​ ​t​h​i​s​ ​f​a​r​.
		 */
		TOP2: string
	}
	menus: {
		/**
		 * C​o​p​y​ ​I​D
		 */
		COPY_ID: string
		/**
		 * M​a​r​k​ ​a​s​ ​R​e​a​d
		 */
		MARK_AS_READ: string
		/**
		 * I​n​v​i​t​e​ ​P​e​o​p​l​e
		 */
		INVITE_PEOPLE: string
		msg: {
			/**
			 * D​e​l​e​t​e​ ​M​e​s​s​a​g​e
			 */
			DELETE: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​?
			 */
			CONFIRM: string
			/**
			 * E​d​i​t​ ​M​e​s​s​a​g​e
			 */
			EDIT: string
			/**
			 * C​o​p​y​ ​M​e​s​s​a​g​e
			 */
			COPY: string
			/**
			 * C​o​p​y​ ​S​e​l​e​c​t​i​o​n
			 */
			COPY_SEL: string
			/**
			 * R​e​p​o​r​t​ ​M​e​s​s​a​g​e
			 */
			REPORT: string
		}
		room: {
			/**
			 * E​d​i​t​ ​C​h​a​n​n​e​l
			 */
			EDIT: string
		}
		room_list: {
			/**
			 * C​r​e​a​t​e​ ​C​h​a​n​n​e​l
			 */
			CREATE: string
		}
	}
	member_list: {
		/**
		 * {​r​o​l​e​}​ ​–​ ​{​l​e​n​g​t​h​|​n​u​m​b​e​r​}
		 * @param {number} length
		 * @param {string} role
		 */
		ROLE: RequiredParams<'length|number' | 'role'>
	}
	lightbox: {
		/**
		 *  ​—​ ​{​w​i​d​t​h​|​n​u​m​b​e​r​}​ ​x​ ​{​h​e​i​g​h​t​|​n​u​m​b​e​r​}​ ​(​{​s​i​z​e​|​b​y​t​e​s​}​)
		 * @param {number} height
		 * @param {number} size
		 * @param {number} width
		 */
		META: RequiredParams<'height|number' | 'size|bytes' | 'width|number'>
	}
	settings: {
		/**
		 * A​c​c​o​u​n​t
		 */
		ACCOUNT: string
		/**
		 * P​r​o​f​i​l​e
		 */
		PROFILE: string
		/**
		 * P​r​i​v​a​c​y
		 */
		PRIVACY: string
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		NOTIFICATIONS: string
		/**
		 * A​p​p​e​a​r​a​n​c​e
		 */
		APPEARANCE: string
		/**
		 * A​c​c​e​s​s​i​b​i​l​i​t​y
		 */
		ACCESSIBILITY: string
		/**
		 * T​e​x​t​ ​&​ ​M​e​d​i​a
		 */
		TEXT_AND_MEDIA: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		LANGUAGE: string
		/**
		 * L​o​g​o​u​t
		 */
		LOGOUT: string
		/**
		 * R​e​t​u​r​n
		 */
		RETURN: string
		/**
		 * S​e​l​e​c​t​ ​a​n​y​ ​c​a​t​e​g​o​r​y​ ​t​o​ ​v​i​e​w​ ​s​e​t​t​i​n​g​s
		 */
		SELECT_CATEGORY: string
		account: {
			/**
			 * {​u​s​e​d​|​b​y​t​e​s​}​/​{​t​o​t​a​l​|​b​y​t​e​s​}​ ​(​{​p​e​r​c​e​n​t​|​p​e​r​c​e​n​t​}​)​ ​U​p​l​o​a​d​ ​Q​u​o​t​a​ ​U​s​e​d
			 * @param {number} percent
			 * @param {number} total
			 * @param {number} used
			 */
			QUOTA: RequiredParams<'percent|percent' | 'total|bytes' | 'used|bytes'>
			/**
			 * E​n​a​b​l​e​ ​D​e​v​e​l​o​p​e​r​ ​M​o​d​e
			 */
			DEV_MODE: string
		}
		appearance: {
			/**
			 * T​h​e​m​e
			 */
			THEME: string
			/**
			 * S​h​o​w​ ​L​i​n​e​s​ ​B​e​t​w​e​e​n​ ​G​r​o​u​p​s
			 */
			GROUP_LINES: string
			/**
			 * G​r​o​u​p​ ​P​a​d​d​i​n​g
			 */
			GROUP_PADDING: string
			/**
			 * L​i​g​h​t​ ​T​h​e​m​e
			 */
			LIGHT_THEME: string
			/**
			 * D​a​r​k​ ​T​h​e​m​e
			 */
			DARK_THEME: string
			/**
			 * E​n​a​b​l​e​ ​O​L​E​D​ ​D​a​r​k​ ​T​h​e​m​e
			 */
			OLED_THEME: string
			/**
			 * T​e​m​p​e​r​a​t​u​r​e
			 */
			TEMP: string
			/**
			 * V​i​e​w​ ​M​o​d​e
			 */
			VIEW_MODE: string
			/**
			 * C​o​m​p​a​c​t
			 */
			COMPACT: string
			/**
			 * C​o​z​y
			 */
			COZY: string
			/**
			 * "​T​h​e​ ​w​i​z​a​r​d​ ​q​u​i​c​k​l​y​ ​j​i​n​x​e​d​ ​t​h​e​ ​g​n​o​m​e​s​ ​b​e​f​o​r​e​ ​t​h​e​y​ ​v​a​p​o​r​i​z​e​d​.​"
			 */
			FONT_EXAMPLE: string
			/**
			 * C​h​a​t​ ​F​o​n​t​ ​S​i​z​e
			 */
			CHAT_FONT_SIZE: string
			/**
			 * U​I​ ​F​o​n​t​ ​S​i​z​e
			 */
			UI_FONT_SIZE: string
			/**
			 * C​h​a​t​ ​F​o​n​t​ ​F​a​m​i​l​y
			 */
			CHAT_FONT_FAMILY: string
			/**
			 * U​I​ ​F​o​n​t​ ​F​a​m​i​l​y
			 */
			UI_FONT_FAMILY: string
			/**
			 * S​h​o​w​ ​D​a​t​e​ ​C​h​a​n​g​e
			 */
			SHOW_DATE_CHANGE: string
		}
		notifications: {
			ENABLE_DESKTOP_NOTIFICATIONS: {
				/**
				 * E​n​a​b​l​e​ ​D​e​s​k​t​o​p​ ​N​o​t​i​f​i​c​a​t​i​o​n​s
				 */
				'0': string
				/**
				 * E​n​a​b​l​e​ ​D​e​s​k​t​o​p​ ​N​o​t​i​f​i​c​a​t​i​o​n​s​ ​(​M​a​y​ ​b​e​ ​o​u​t​d​a​t​e​d​ ​i​f​ ​r​e​v​o​k​e​d​ ​e​x​t​e​r​n​a​l​l​y​)
				 */
				'1': string
				/**
				 * E​n​a​b​l​e​ ​D​e​s​k​t​o​p​ ​N​o​t​i​f​i​c​a​t​i​o​n​s​ ​(​N​o​t​ ​A​v​a​i​l​a​b​l​e​)
				 */
				'2': string
			}
		}
		media: {
			/**
			 * S​h​o​w​ ​M​e​d​i​a​ ​M​e​t​a​d​a​t​a
			 */
			SHOW_MEDIA_METADATA: string
			/**
			 * D​i​s​p​l​a​y​s​ ​f​i​l​e​ ​n​a​m​e​,​ ​M​I​M​E​ ​t​y​p​e​,​ ​a​n​d​ ​f​i​l​e​ ​s​i​z​e​ ​o​n​ ​a​t​t​a​c​h​m​e​n​t​s
			 */
			SHOW_MEDIA_METADATA_SUBTEXT: string
			/**
			 * M​u​t​e​ ​M​e​d​i​a​ ​b​y​ ​D​e​f​a​u​l​t
			 */
			MUTE_MEDIA: string
			/**
			 * D​i​s​a​b​l​e​ ​A​t​t​a​c​h​m​e​n​t​s​ ​o​f​ ​U​n​k​n​o​w​n​ ​S​i​z​e
			 */
			HIDE_UNKNOWN: string
			/**
			 * U​s​e​ ​P​l​a​t​f​o​r​m​ ​E​m​o​j​i​s
			 */
			USE_PLATFORM_EMOJIS: string
			/**
			 * E​n​a​b​l​e​ ​S​p​e​l​l​c​h​e​c​k
			 */
			ENABLE_SPELLCHECK: string
		}
		accessibility: {
			/**
			 * R​e​d​u​c​e​ ​M​o​t​i​o​n
			 */
			REDUCE_MOTION: string
			/**
			 * R​e​d​u​c​e​s​ ​o​r​ ​r​e​m​o​v​e​s​ ​a​n​i​m​a​t​i​o​n​s​ ​a​n​d​ ​t​r​a​n​s​i​t​i​o​n​s
			 */
			REDUCE_MOTION_SUBTEXT: string
			/**
			 * P​a​u​s​e​ ​G​I​F​s​ ​o​n​ ​U​n​f​o​c​u​s
			 */
			UNFOCUS_PAUSE: string
			/**
			 * E​n​a​b​l​e​ ​L​o​w​-​B​a​n​d​w​i​d​t​h​ ​M​o​d​e
			 */
			LOW_BANDWIDTH: string
			/**
			 * U​s​e​s​ ​l​o​w​e​r​ ​q​u​a​l​i​t​y​ ​a​s​s​e​t​s​ ​a​n​d​ ​w​i​l​l​ ​n​o​t​ ​d​i​s​p​l​a​y​ ​a​t​t​a​c​h​m​e​n​t​s​ ​u​n​t​i​l​ ​r​e​q​u​e​s​t​e​d
			 */
			LOW_BANDWIDTH_SUBTEXT: string
			/**
			 * F​o​r​c​e​ ​C​o​n​s​t​r​a​s​t​i​n​g​ ​C​o​l​o​r​s
			 */
			FORCE_COLOR_CONTRAST: string
			/**
			 * A​d​j​u​s​t​s​ ​c​u​s​t​o​m​ ​c​o​l​o​r​s​ ​f​r​o​m​ ​u​s​e​r​s​ ​o​r​ ​r​o​l​e​s​ ​t​o​ ​b​e​ ​v​i​s​i​b​l​e​ ​a​g​a​i​n​s​t​ ​t​h​e​ ​b​a​c​k​g​r​o​u​n​d
			 */
			FORCE_COLOR_CONTRAST_SUBTEXT: string
		}
		profile: {
			/**
			 * A​v​a​t​a​r​ ​R​o​u​n​d​n​e​s​s
			 */
			AVATAR_ROUNDNESS: string
			/**
			 * S​t​a​t​u​s
			 */
			STATUS: string
			/**
			 * B​i​o​g​r​a​p​h​y
			 */
			BIO: string
			/**
			 * C​h​a​n​g​e​ ​A​v​a​t​a​r
			 */
			CHANGE_AVATAR: string
			/**
			 * C​h​a​n​g​e​ ​B​a​n​n​e​r
			 */
			CHANGE_BANNER: string
			/**
			 * R​e​m​o​v​e​ ​A​v​a​t​a​r
			 */
			REMOVE_AVATAR: string
			/**
			 * R​e​m​o​v​e​ ​B​a​n​n​e​r
			 */
			REMOVE_BANNER: string
		}
	}
	system: {
		welcome: {
			/**
			 * W​e​l​c​o​m​e​,​ ​<​@​{​u​s​e​r​}​>​!
			 * @param {string} user
			 */
			'0': RequiredParams<'user'>
			/**
			 * <​@​{​u​s​e​r​}​>​ ​h​a​s​ ​j​o​i​n​e​d​ ​t​h​e​ ​p​a​r​t​y​!
			 * @param {string} user
			 */
			'1': RequiredParams<'user'>
			/**
			 * <​@​{​u​s​e​r​}​>​ ​i​s​ ​h​e​r​e​,​ ​s​c​a​t​t​e​r​!
			 * @param {string} user
			 */
			'2': RequiredParams<'user'>
		}
	}
}

export type Namespaces =
	| 'main'

type DisallowNamespaces = {
	/**
	 * reserved for 'main'-namespace\
	 * you need to use the `./main/index.ts` file instead
	 */
	main?: "[typesafe-i18n] reserved for 'main'-namespace. You need to use the `./main/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * This is a development build.
	 */
	DEV_BANNER: () => LocalizedString
	/**
	 * Year
	 */
	YEAR: () => LocalizedString
	/**
	 * Month
	 */
	MONTH: () => LocalizedString
	/**
	 * Day
	 */
	DAY: () => LocalizedString
	/**
	 * Register
	 */
	REGISTER: () => LocalizedString
	/**
	 * Login
	 */
	LOGIN: () => LocalizedString
	/**
	 * Email Address
	 */
	EMAIL_ADDRESS: () => LocalizedString
	/**
	 * Username
	 */
	USERNAME: () => LocalizedString
	/**
	 * Username or Email
	 */
	USERNAME_OR_EMAIL: () => LocalizedString
	/**
	 * Nickname
	 */
	NICKNAME: () => LocalizedString
	/**
	 * Password
	 */
	PASSWORD: () => LocalizedString
	/**
	 * Reset
	 */
	RESET: () => LocalizedString
	/**
	 * Date of Birth
	 */
	DATE_OF_BIRTH: () => LocalizedString
	/**
	 * Network Error
	 */
	NETWORK_ERROR: () => LocalizedString
	/**
	 * Unknown Error
	 */
	UNKNOWN_ERROR: () => LocalizedString
	/**
	 * {{Don't have|Have}} a 2FA code?
	 */
	MFA_TOGGLE_TEXT: (arg: { h: string | number | boolean }) => LocalizedString
	/**
	 * Click here to {{hide|show}} the input.
	 */
	MFA_TOGGLE_FLAVOR: (arg: { h: string | number | boolean }) => LocalizedString
	/**
	 * 2FA Code
	 */
	MFA_CODE: () => LocalizedString
	/**
	 * Go to Login
	 */
	GOTO_LOGIN: () => LocalizedString
	/**
	 * By registering, you agree to our... this will be filled in later.
	 */
	REGISTER_AGREE: () => LocalizedString
	/**
	 * Password must be at least 8 characters long and contain at least one number or one special character.
	 */
	PASSWORD_REQS: () => LocalizedString
	/**
	 * Change Theme
	 */
	CHANGE_THEME: () => LocalizedString
	/**
	 * Change Theme Temperature
	 */
	CHANGE_THEME_TEMP: () => LocalizedString
	/**
	 * Change Language
	 */
	CHANGE_LANG: () => LocalizedString
	/**
	 * Loading...
	 */
	LOADING: () => LocalizedString
	/**
	 * dddd, MMMM Do, YYYY LT
	 */
	DEFAULT_TS_FORMAT: () => LocalizedString
	CALENDAR_FORMAT: {
		/**
		 * [Yesterday at] LT
		 */
		lastDay: () => LocalizedString
		/**
		 * [Today at] LT
		 */
		sameDay: () => LocalizedString
		/**
		 * [Tomorrow at] LT
		 */
		nextDay: () => LocalizedString
		/**
		 * dddd [at] LT
		 */
		nextWeek: () => LocalizedString
		/**
		 * [Last] dddd [at] LT
		 */
		lastWeek: () => LocalizedString
		/**
		 * L
		 */
		sameElse: () => LocalizedString
	}
	/**
	 * This site is protected by hCaptcha and its <@Privacy Policy> and <#Terms of Service> apply.
	 */
	hCaptcha: () => LocalizedString
	units: {
		/**
		 * {0}px
		 */
		PX: (arg0: unknown) => LocalizedString
	}
	main: {
		/**
		 * Channel
		 */
		CHANNEL: () => LocalizedString
		/**
		 * Party
		 */
		PARTY: () => LocalizedString
		/**
		 * Direct Message
		 */
		DIRECT_MESSAGE: () => LocalizedString
		/**
		 * Create Direct Message
		 */
		CREATE_DIRECT_MESSAGE: () => LocalizedString
		/**
		 * {{✔|}} Bot
		 */
		BOT: (arg: { verified: string | number | boolean }) => LocalizedString
		/**
		 * Online
		 */
		ONLINE: () => LocalizedString
		/**
		 * Offline
		 */
		OFFLINE: () => LocalizedString
		/**
		 * Busy/Do Not Disturb
		 */
		BUSY: () => LocalizedString
		/**
		 * Away
		 */
		AWAY: () => LocalizedString
		/**
		 * Message
		 */
		MESSAGE: () => LocalizedString
		/**
		 * Settings
		 */
		SETTINGS: () => LocalizedString
		/**
		 * Mute
		 */
		MUTE: () => LocalizedString
		/**
		 * Unmute
		 */
		UNMUTE: () => LocalizedString
		/**
		 * Deafen
		 */
		DEAFEN: () => LocalizedString
		/**
		 * Undeafen
		 */
		UNDEAFEN: () => LocalizedString
		/**
		 * Edited
		 */
		EDITED: () => LocalizedString
		/**
		 * Edited on {ts|timestamp}
		 */
		EDITED_ON: (arg: { ts: unknown }) => LocalizedString
		/**
		 * Pinned
		 */
		PINNED: () => LocalizedString
		/**
		 * Message Pinned
		 */
		MESSAGE_PINNED: () => LocalizedString
		/**
		 * Owner
		 */
		OWNER: () => LocalizedString
		/**
		 * You're viewing older messages.
		 */
		VIEWING_OLDER: () => LocalizedString
		/**
		 * Go to now
		 */
		GOTO_NOW: () => LocalizedString
		/**
		 * Click to reveal spoiler
		 */
		SPOILER_TITLE: () => LocalizedString
		/**
		 * {{Uns|S}}poiler
		 */
		SPOILER: (arg0: string | number | boolean) => LocalizedString
		/**
		 * {{Uns|S}}poiler All
		 */
		SPOILER_ALL: (arg0: string | number | boolean) => LocalizedString
		/**
		 * Remove
		 */
		REMOVE: () => LocalizedString
		/**
		 * Remove All
		 */
		REMOVE_ALL: () => LocalizedString
		/**
		 * Save
		 */
		SAVE: () => LocalizedString
		/**
		 * Continue Editing
		 */
		CONTINUE: () => LocalizedString
		/**
		 * Discard
		 */
		DISCARD: () => LocalizedString
		/**
		 * Reset
		 */
		RESET: () => LocalizedString
		/**
		 * You have unsaved changes!
		 */
		UNSAVED: () => LocalizedString
		/**
		 * Attach File
		 */
		ATTACH_FILE: () => LocalizedString
		/**
		 * Send Message
		 */
		SEND_MESSAGE: () => LocalizedString
		/**
		 * Drop Files
		 */
		DROP_FILES: () => LocalizedString
		USERS_TYPING: {
			/**
			 * {0} is typing...
			 */
			'0': (arg0: string) => LocalizedString
			/**
			 * {0} and {1} are typing...
			 */
			'1': (arg0: string, arg1: string) => LocalizedString
			/**
			 * {0}, {1}, and {2} are typing...
			 */
			'2': (arg0: string, arg1: string, arg2: string) => LocalizedString
			/**
			 * {0}, {1}, {2}, and {3} others are typing...
			 */
			'3': (arg0: string, arg1: string, arg2: string, arg3: number) => LocalizedString
		}
		channel: {
			/**
			 * You have reached the top of #{0}!
			 */
			TOP1: (arg0: unknown) => LocalizedString
			/**
			 * Congrats on making it this far.
			 */
			TOP2: () => LocalizedString
		}
		menus: {
			/**
			 * Copy ID
			 */
			COPY_ID: () => LocalizedString
			/**
			 * Mark as Read
			 */
			MARK_AS_READ: () => LocalizedString
			/**
			 * Invite People
			 */
			INVITE_PEOPLE: () => LocalizedString
			msg: {
				/**
				 * Delete Message
				 */
				DELETE: () => LocalizedString
				/**
				 * Are you sure?
				 */
				CONFIRM: () => LocalizedString
				/**
				 * Edit Message
				 */
				EDIT: () => LocalizedString
				/**
				 * Copy Message
				 */
				COPY: () => LocalizedString
				/**
				 * Copy Selection
				 */
				COPY_SEL: () => LocalizedString
				/**
				 * Report Message
				 */
				REPORT: () => LocalizedString
			}
			room: {
				/**
				 * Edit Channel
				 */
				EDIT: () => LocalizedString
			}
			room_list: {
				/**
				 * Create Channel
				 */
				CREATE: () => LocalizedString
			}
		}
		member_list: {
			/**
			 * {role} – {length|number}
			 */
			ROLE: (arg: { length: number, role: string }) => LocalizedString
		}
		lightbox: {
			/**
			 *  — {width|number} x {height|number} ({size|bytes})
			 */
			META: (arg: { height: number, size: number, width: number }) => LocalizedString
		}
		settings: {
			/**
			 * Account
			 */
			ACCOUNT: () => LocalizedString
			/**
			 * Profile
			 */
			PROFILE: () => LocalizedString
			/**
			 * Privacy
			 */
			PRIVACY: () => LocalizedString
			/**
			 * Notifications
			 */
			NOTIFICATIONS: () => LocalizedString
			/**
			 * Appearance
			 */
			APPEARANCE: () => LocalizedString
			/**
			 * Accessibility
			 */
			ACCESSIBILITY: () => LocalizedString
			/**
			 * Text & Media
			 */
			TEXT_AND_MEDIA: () => LocalizedString
			/**
			 * Language
			 */
			LANGUAGE: () => LocalizedString
			/**
			 * Logout
			 */
			LOGOUT: () => LocalizedString
			/**
			 * Return
			 */
			RETURN: () => LocalizedString
			/**
			 * Select any category to view settings
			 */
			SELECT_CATEGORY: () => LocalizedString
			account: {
				/**
				 * {used|bytes}/{total|bytes} ({percent|percent}) Upload Quota Used
				 */
				QUOTA: (arg: { percent: number, total: number, used: number }) => LocalizedString
				/**
				 * Enable Developer Mode
				 */
				DEV_MODE: () => LocalizedString
			}
			appearance: {
				/**
				 * Theme
				 */
				THEME: () => LocalizedString
				/**
				 * Show Lines Between Groups
				 */
				GROUP_LINES: () => LocalizedString
				/**
				 * Group Padding
				 */
				GROUP_PADDING: () => LocalizedString
				/**
				 * Light Theme
				 */
				LIGHT_THEME: () => LocalizedString
				/**
				 * Dark Theme
				 */
				DARK_THEME: () => LocalizedString
				/**
				 * Enable OLED Dark Theme
				 */
				OLED_THEME: () => LocalizedString
				/**
				 * Temperature
				 */
				TEMP: () => LocalizedString
				/**
				 * View Mode
				 */
				VIEW_MODE: () => LocalizedString
				/**
				 * Compact
				 */
				COMPACT: () => LocalizedString
				/**
				 * Cozy
				 */
				COZY: () => LocalizedString
				/**
				 * "The wizard quickly jinxed the gnomes before they vaporized."
				 */
				FONT_EXAMPLE: () => LocalizedString
				/**
				 * Chat Font Size
				 */
				CHAT_FONT_SIZE: () => LocalizedString
				/**
				 * UI Font Size
				 */
				UI_FONT_SIZE: () => LocalizedString
				/**
				 * Chat Font Family
				 */
				CHAT_FONT_FAMILY: () => LocalizedString
				/**
				 * UI Font Family
				 */
				UI_FONT_FAMILY: () => LocalizedString
				/**
				 * Show Date Change
				 */
				SHOW_DATE_CHANGE: () => LocalizedString
			}
			notifications: {
				ENABLE_DESKTOP_NOTIFICATIONS: {
					/**
					 * Enable Desktop Notifications
					 */
					'0': () => LocalizedString
					/**
					 * Enable Desktop Notifications (May be outdated if revoked externally)
					 */
					'1': () => LocalizedString
					/**
					 * Enable Desktop Notifications (Not Available)
					 */
					'2': () => LocalizedString
				}
			}
			media: {
				/**
				 * Show Media Metadata
				 */
				SHOW_MEDIA_METADATA: () => LocalizedString
				/**
				 * Displays file name, MIME type, and file size on attachments
				 */
				SHOW_MEDIA_METADATA_SUBTEXT: () => LocalizedString
				/**
				 * Mute Media by Default
				 */
				MUTE_MEDIA: () => LocalizedString
				/**
				 * Disable Attachments of Unknown Size
				 */
				HIDE_UNKNOWN: () => LocalizedString
				/**
				 * Use Platform Emojis
				 */
				USE_PLATFORM_EMOJIS: () => LocalizedString
				/**
				 * Enable Spellcheck
				 */
				ENABLE_SPELLCHECK: () => LocalizedString
			}
			accessibility: {
				/**
				 * Reduce Motion
				 */
				REDUCE_MOTION: () => LocalizedString
				/**
				 * Reduces or removes animations and transitions
				 */
				REDUCE_MOTION_SUBTEXT: () => LocalizedString
				/**
				 * Pause GIFs on Unfocus
				 */
				UNFOCUS_PAUSE: () => LocalizedString
				/**
				 * Enable Low-Bandwidth Mode
				 */
				LOW_BANDWIDTH: () => LocalizedString
				/**
				 * Uses lower quality assets and will not display attachments until requested
				 */
				LOW_BANDWIDTH_SUBTEXT: () => LocalizedString
				/**
				 * Force Constrasting Colors
				 */
				FORCE_COLOR_CONTRAST: () => LocalizedString
				/**
				 * Adjusts custom colors from users or roles to be visible against the background
				 */
				FORCE_COLOR_CONTRAST_SUBTEXT: () => LocalizedString
			}
			profile: {
				/**
				 * Avatar Roundness
				 */
				AVATAR_ROUNDNESS: () => LocalizedString
				/**
				 * Status
				 */
				STATUS: () => LocalizedString
				/**
				 * Biography
				 */
				BIO: () => LocalizedString
				/**
				 * Change Avatar
				 */
				CHANGE_AVATAR: () => LocalizedString
				/**
				 * Change Banner
				 */
				CHANGE_BANNER: () => LocalizedString
				/**
				 * Remove Avatar
				 */
				REMOVE_AVATAR: () => LocalizedString
				/**
				 * Remove Banner
				 */
				REMOVE_BANNER: () => LocalizedString
			}
		}
		system: {
			welcome: {
				/**
				 * Welcome, <@{user}>!
				 */
				'0': (arg: { user: string }) => LocalizedString
				/**
				 * <@{user}> has joined the party!
				 */
				'1': (arg: { user: string }) => LocalizedString
				/**
				 * <@{user}> is here, scatter!
				 */
				'2': (arg: { user: string }) => LocalizedString
			}
		}
	}
}

export type Formatters = {
	bytes: (value: number) => unknown
	number: (value: number) => unknown
	percent: (value: number) => unknown
	timestamp: (value: unknown) => unknown
}
