// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Channel
	 */
	CHANNEL: string
	/**
	 * Party
	 */
	PARTY: string
	/**
	 * Direct Message
	 */
	DIRECT_MESSAGE: string
	/**
	 * Create Direct Message
	 */
	CREATE_DIRECT_MESSAGE: string
	/**
	 * Year
	 */
	YEAR: string
	/**
	 * Month
	 */
	MONTH: string
	/**
	 * Day
	 */
	DAY: string
	/**
	 * January,February,March,April,May,June,July,August,September,October,November,December
	 */
	MONTHS: string
	/**
	 * Register
	 */
	REGISTER: string
	/**
	 * Login
	 */
	LOGIN: string
	/**
	 * Email Address
	 */
	EMAIL_ADDRESS: string
	/**
	 * Username
	 */
	USERNAME: string
	/**
	 * Username or Email
	 */
	USERNAME_OR_EMAIL: string
	/**
	 * Nickname
	 */
	NICKNAME: string
	/**
	 * Password
	 */
	PASSWORD: string
	/**
	 * Reset
	 */
	RESET: string
	/**
	 * Date of Birth
	 */
	DATE_OF_BIRTH: string
	/**
	 * Network Error
	 */
	NETWORK_ERROR: string
	/**
	 * Unknown Error
	 */
	UNKNOWN_ERROR: string
	/**
	 * {h|{true: Don't have, false: Have}} a 2FA Code?
	 * @param {'false' | 'true'} h
	 */
	MFA_TOGGLE_TEXT: RequiredParams<`h|{true:${string}, false:${string}}`>
	/**
	 * Click here to {h|{true: hide, false: show}} the input.
	 * @param {'false' | 'true'} h
	 */
	MFA_TOGGLE_FLAVOR: RequiredParams<`h|{true:${string}, false:${string}}`>
	/**
	 * 2FA Code
	 */
	MFA_CODE: string
}

export type TranslationFunctions = {
	/**
	 * Channel
	 */
	CHANNEL: () => LocalizedString
	/**
	 * Party
	 */
	PARTY: () => LocalizedString
	/**
	 * Direct Message
	 */
	DIRECT_MESSAGE: () => LocalizedString
	/**
	 * Create Direct Message
	 */
	CREATE_DIRECT_MESSAGE: () => LocalizedString
	/**
	 * Year
	 */
	YEAR: () => LocalizedString
	/**
	 * Month
	 */
	MONTH: () => LocalizedString
	/**
	 * Day
	 */
	DAY: () => LocalizedString
	/**
	 * January,February,March,April,May,June,July,August,September,October,November,December
	 */
	MONTHS: () => LocalizedString
	/**
	 * Register
	 */
	REGISTER: () => LocalizedString
	/**
	 * Login
	 */
	LOGIN: () => LocalizedString
	/**
	 * Email Address
	 */
	EMAIL_ADDRESS: () => LocalizedString
	/**
	 * Username
	 */
	USERNAME: () => LocalizedString
	/**
	 * Username or Email
	 */
	USERNAME_OR_EMAIL: () => LocalizedString
	/**
	 * Nickname
	 */
	NICKNAME: () => LocalizedString
	/**
	 * Password
	 */
	PASSWORD: () => LocalizedString
	/**
	 * Reset
	 */
	RESET: () => LocalizedString
	/**
	 * Date of Birth
	 */
	DATE_OF_BIRTH: () => LocalizedString
	/**
	 * Network Error
	 */
	NETWORK_ERROR: () => LocalizedString
	/**
	 * Unknown Error
	 */
	UNKNOWN_ERROR: () => LocalizedString
	/**
	 * {h|{true: Don't have, false: Have}} a 2FA Code?
	 */
	MFA_TOGGLE_TEXT: (arg: { h: 'false' | 'true' }) => LocalizedString
	/**
	 * Click here to {h|{true: hide, false: show}} the input.
	 */
	MFA_TOGGLE_FLAVOR: (arg: { h: 'false' | 'true' }) => LocalizedString
	/**
	 * 2FA Code
	 */
	MFA_CODE: () => LocalizedString
}

export type Formatters = {}
